import type { ModeConfig } from "./types.js";

export const engineeringConfig: ModeConfig = {
  id: "engineering",
  name: "Ritual Engineering Graph",
  shortName: "Engineering",
  description: "Engineering wiki, meeting ingestion, feature tracking.",
  accent: "#3BE65B",
  accentLight: "#9BFFB3",
  entityTypes: [
    {
      id: "feature",
      label: "Feature",
      labelPlural: "Features",
      icon: "Sparkles",
      fields: [
        { id: "name", label: "Name", type: "string", required: true },
        {
          id: "status",
          label: "Status",
          type: "enum",
          required: false,
          options: ["Planning", "In Progress", "Review", "Done", "Blocked"],
        },
        { id: "description", label: "Description", type: "text", required: false },
        { id: "owner", label: "Owner", type: "string", required: false },
        { id: "epic", label: "Epic", type: "string", required: false },
        { id: "asana_task_id", label: "Asana Task ID", type: "string", required: false },
        { id: "related_topics", label: "Related Topics", type: "text", required: false },
        { id: "related_decisions", label: "Related Decisions", type: "text", required: false },
      ],
      searchableFields: ["name", "description", "owner"],
    },
    {
      id: "decision",
      label: "Decision",
      labelPlural: "Decisions",
      icon: "Gavel",
      fields: [
        { id: "title", label: "Title", type: "string", required: true },
        {
          id: "status",
          label: "Status",
          type: "enum",
          required: false,
          options: ["Proposed", "Accepted", "Deprecated", "Superseded"],
        },
        { id: "context", label: "Context", type: "text", required: false },
        { id: "decision", label: "Decision", type: "text", required: false },
        { id: "consequences", label: "Consequences", type: "text", required: false },
        { id: "decided_at", label: "Decided At", type: "date", required: false },
        { id: "related_topics", label: "Related Topics", type: "text", required: false },
        { id: "superseded_by", label: "Superseded By", type: "string", required: false },
      ],
      searchableFields: ["title", "context", "decision"],
    },
    {
      id: "topic",
      label: "Topic",
      labelPlural: "Topics",
      icon: "Hash",
      fields: [
        { id: "name", label: "Name", type: "string", required: true },
        { id: "description", label: "Description", type: "text", required: false },
        {
          id: "category",
          label: "Category",
          type: "enum",
          required: false,
          options: ["Architecture", "Infrastructure", "Frontend", "Backend", "DevOps", "Process"],
        },
        { id: "wiki_content", label: "Wiki Content", type: "text", required: false },
        { id: "related_features", label: "Related Features", type: "text", required: false },
        { id: "related_decisions", label: "Related Decisions", type: "text", required: false },
      ],
      searchableFields: ["name", "description", "wiki_content"],
    },
    {
      id: "component",
      label: "Component",
      labelPlural: "Components",
      icon: "Puzzle",
      fields: [
        { id: "name", label: "Name", type: "string", required: true },
        {
          id: "type",
          label: "Type",
          type: "enum",
          required: false,
          options: ["Service", "Library", "API", "UI", "Database", "Infrastructure"],
        },
        { id: "description", label: "Description", type: "text", required: false },
        { id: "repository", label: "Repository", type: "url", required: false },
        { id: "owned_by", label: "Owned By", type: "string", required: false },
        { id: "dependencies", label: "Dependencies", type: "text", required: false },
        { id: "related_features", label: "Related Features", type: "text", required: false },
      ],
      searchableFields: ["name", "description", "owned_by"],
    },
  ],
  pipelineStages: [
    {
      id: "meet-transcript",
      name: "Meeting Transcript",
      description: "Normalize Google Meet transcript input",
      handler: "scripts/stages/meeting-transcript",
      provider: "claude",
      required: true,
      order: 1,
    },
    {
      id: "engineering-entities",
      name: "Engineering Extraction",
      description: "Extract topics, decisions, features, and components",
      handler: "scripts/stages/engineering-entities",
      provider: "claude",
      required: true,
      order: 2,
    },
    {
      id: "engineering-wiki",
      name: "Wiki + Outputs",
      description: "Generate wiki pages and feature tracking outputs",
      handler: "scripts/stages/engineering-wiki",
      provider: "claude",
      required: true,
      order: 3,
    },
    {
      id: "engineering-sync",
      name: "Graph Sync",
      description: "Sync engineering entities to the database",
      handler: "scripts/stages/engineering-sync",
      provider: "internal",
      required: true,
      order: 4,
    },
    {
      id: "asana-import",
      name: "Asana Import",
      description: "One-way import of feature tasks",
      handler: "scripts/stages/asana-import",
      provider: "internal",
      required: false,
      order: 5,
    },
  ],
  navigation: {
    defaultPath: "/dashboard",
    items: [
      { label: "Dashboard", path: "/dashboard", icon: "LayoutDashboard" },
      { label: "Wiki", path: "/wiki", icon: "BookOpen" },
      { label: "Features", path: "/features", icon: "Sparkles" },
      { label: "Decisions", path: "/decisions", icon: "Gavel" },
      { label: "Components", path: "/components", icon: "Puzzle" },
    ],
  },
  features: {
    crossLinking: false,
    externalIntegrations: ["asana", "google-drive", "gemini"],
  },
};
